### ISSUE TITLE
TypeError: Discord.MessageEmbed is not a constructor

### ISSUE THREAD

**Issue by thepigeonfighter** [yugoccp/slack2discord#23]
Hey there, 
Thanks for your work on this. I was trying to run a conversion. It looks like it parsed all the files and then throws this error:

TypeError: Discord.MessageEmbed is not a constructor
    at C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\src\messageParser.js:119:21
    at Array.map (<anonymous>)
    at getEmbeds (C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\src\messageParser.js:118:32)
    at C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\src\messageParser.js:27:15
    at Array.reduce (<anonymous>)
    at Object.parseMessages (C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\src\messageParser.js:15:24)
    at C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\src\commands\parseMessages.js:28:44
    
 Using node 16.15.1 and slack2Discord 1.0.4

Any help would be appreciated.

**Comment by yugoccp** [comment]
Hi @thepigeonfighter ! Fixed issue on Embed message, please try again with version 1.0.5 :)

**Comment by thepigeonfighter** [comment]
Hey @yugoccp thanks for the reply and quick patch. That did indeed fix the error, but I am now getting this error: 

```
C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\node_modules\@sapphire\shapeshift\dist\index.js:1161
      return Result.err(new ValidationError("s.object(T)", `Expected the value to be an object, but received ${typeOfValue} instead`, value));
                        ^

ValidationError: Expected the value to be an object, but received string instead
    at ObjectValidator.handle (C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\node_modules\@sapphire\shapeshift\dist\index.js:1161:25)
    at ObjectValidator.parse (C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\node_modules\@sapphire\shapeshift\dist\index.js:113:88)
    at EmbedBuilder.setFooter (C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\node_modules\@discordjs\builders\dist\messages\embed\Embed.cjs:66:37)
    at C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\src\messageParser.js:124:29
    at Array.map (<anonymous>)
    at getEmbeds (C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\src\messageParser.js:118:32)
    at C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\src\messageParser.js:27:15
    at Array.reduce (<anonymous>)
    at Object.parseMessages (C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\src\messageParser.js:15:24)
    at C:\ProgramData\nvm\v16.15.1\node_modules\slack2discord\src\commands\parseMessages.js:28:44 {
  validator: 's.object(T)',
  given: 'Thread in #unclemikesslightlylegalplayground'
}
```




Thanks for your help!

**Comment by yugoccp** [comment]
hey @thepigeonfighter ! Fixed this bug in 1.0.7 but having issues at Discord to actually show the embedded messages :(... something might changed on their API, have to take a deeper look on it.
